### PR TITLE
wxPython 2.8 compatibility: SendSizeEventToParent and SetNativeFontInfo

### PR DESCRIPTION
**Pull request by Jorilx**
Added compat.SendSizeEventToParent
Adapted SetNativeFontInfo call to wxPython 2.8

### CODE REVIEW

**Comment by DietmarSchwertberger** [comment]
Thanks a lot.

**Comment by DietmarSchwertberger** [comment]
Regarding font size changes:
StaticText is not a real widget with  GTK.

You may want to change EditStaticText._properties_changed to  add "recreate2" under certain conditions, i.e. font change and 2.8 and __WXGTK__.

Alternatively, if you also observe mouse event problems on this platform you may want to use lib.gen.StatText again in create_widget.
Until 0.7.2  that was used. I went away mainly for unwanted behaviour on Windows, e.g. when people are using screen readers.

**Comment by Jorilx** [comment]
I see, thanks! I'll make another PR

**Comment by DietmarSchwertberger** [comment]
Well, I just read your message on the list.
Does swapping these lines fix your problem with 2.8?


```
WindowBase.on_size:

        if event.GetEventObject() is None: return
        event.Skip()
```

If yes, I will do so. I think it's safe.

**Comment by Jorilx** [comment]
Yes it works! This is way cleaner than PR #437 :)

**Comment by DietmarSchwertberger** [comment]
OK, then I will undo #437 and implement this modification instead.

**Comment by DietmarSchwertberger** [comment]
1.0.0a5 is online. Next update after the weekend only.

**Pull request merged**
